# Generated by Django 3.2.16 on 2022-10-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название книги')),
                ('author', models.CharField(max_length=40, verbose_name='Автор')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
            options={
                'db_table': 'Bookshop',
            },
        ),
    ]
